name: Nightly

on:
  push:
  workflow_dispatch: 

permissions:
  contents: read

jobs:
  build:
    if: "${{ github.event_name == 'workflow_dispatch' || !startsWith(github.event.head_commit.message, 'chore(master): release') }}"
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1

      - name: Setup pnpm
        uses: pnpm/setup@fbda4c85fc2e1e08721cd8763afea8f48d60f024

      - name: Setup Node.js
        uses: actions/setup-node@820762786026740c76f36085b0efc47a31fe5020
        with:
          node-version: 24.x

      - name: Install dependencies
        run: pnpm ci

      - name: Build UserScript
        run: pnpm run build

      - name: Upload nightly artifact (*.meta.js)
        uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a
        with:
          path: dist/*.meta.js
          if-no-files-found: error

      - name: Upload nightly artifact (*.user.js)
        uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a
        with:
          path: dist/*.user.js
          if-no-files-found: error
