name: Release

on:
  push:
    branches: 
      - master

permissions: 
  contents: write
  issues: write
  pull-requests: write

jobs:
  release_please:
    runs-on: ubuntu-latest
    outputs:
      releases_created: ${{ steps.release_please.outputs.releases_created }}
      tag_name: ${{ steps.release_please.outputs.tag_name }}
    steps:
      - id: release_please
        uses: googleapis/release-please-action@45996ed1f6d02564a971a2fa1b5860e934307cf7

  release:
    needs: release_please
    if: needs.release_please.outputs.releases_created == 'true'
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Check out release tag
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1
        with:
          ref: ${{ needs.release_please.outputs.tag_name }}

      - name: Setup pnpm
        uses: pnpm/setup@fbda4c85fc2e1e08721cd8763afea8f48d60f024

      - name: Setup Node.js
        uses: actions/setup-node@820762786026740c76f36085b0efc47a31fe5020
        with:
          node-version: 24.x

      - name: Install dependencies
        run: pnpm ci

      - name: Build UserScript
        run: pnpm run build

      - name: Draft new GitHub release
        uses: softprops/action-gh-release@efb35369e0ad2afab669f228072c1b0d510eae64
        with:
          tag_name: ${{ needs.release_please.outputs.tag_name }}
          draft: true
          files: |
            ./dist/*.meta.js
            ./dist/*.user.js
          fail_on_unmatched_files: true

      - name: Publish GitHub release
        env:
          GH_TOKEN: ${{ github.token }}
        run: gh release edit "${{ needs.release_please.outputs.tag_name }}" --draft=false
